name: Deploy to Azure Container Apps

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Container Apps (Frontend)
        run: |
          az containerapp update --name transitly-frontend \
            --resource-group ${{ secrets.RESOURCE_GROUP }} \
            --environment ${{ secrets.CONTAINER_APP_ENV }} \
            --image amishkumar/myfrontend:v1 \
            --ingress external \


      - name: Deploy to Azure Container Apps (Backend)
        run: |
          az containerapp update --name transitly-backend \
            --resource-group ${{ secrets.RESOURCE_GROUP }} \
            --environment ${{ secrets.CONTAINER_APP_ENV }} \
            --image amishkumar/myapp:v1 \
            --ingress external \
            --set-env-vars SANITY_PROJECT_ID=${{ secrets.SANITY_PROJECT_ID }}
